---
- name: Install kexec-tools
  package:
    name: kexec-tools
    state: present

# Must reboot to reserve memory for kdump in `/sys/kernel/kexec_crash_size`
- name: Ensure that the kdump service is enabled
  service:
    name: kdump
    enabled: true
  register: __kdump_enable_service

- name: Set the kdump_reboot_required fact
  set_fact:
    __kdump_reboot_required: true
  when: __kdump_enable_service is changed

#- name: Find out reserved memory for the crash kernel
#  slurp:
#    src: /sys/kernel/kexec_crash_size
#  register: kexec_crash_size

- include_tasks: ssh.yml
  when:
    - kdump_target.type | d(none) == 'ssh'

- name: Get mode of /etc/kdump.conf if it exists
  stat:
    path: /etc/kdump.conf
  register: __kdump_conf

- name: Generate /etc/kdump.conf
  template:
    src: kdump.conf.j2
    dest: /etc/kdump.conf
    backup: yes
    mode: "{{ __kdump_conf.stat.mode | d('0644') }}"
  # when: kexec_crash_size.content|b64decode|int > 0
  notify: restart kdump

- name: Get mode of /etc/sysconfig/kdump if it exists
  stat:
    path: /etc/sysconfig/kdump
  register: __sysconfig_kdump

- name: Generate /etc/sysconfig/kdump
  template:
    src: kdump.j2
    dest: /etc/sysconfig/kdump
    backup: yes
    mode: "{{ __sysconfig_kdump.stat.mode | d('0644') }}"
  # when: kexec_crash_size.content|b64decode|int > 0
  notify: restart kdump

- name: Fail with the message that reboot is required
  fail:
    msg: "You must reboot the host to apply the settings"
  when: __kdump_reboot_required | bool
  register: __kdump_reboot_fail

